language: java
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: MV7jgyGgs/93NXJKEF8KuBXh5ZRBX7AqSJinfvGbHcoSBpxAnbU+iyGpzQ1Sv1pc5NzORo3HH/rXjR1p7C4SsOU9KuAzPcdVds8rFLK1S2p1ZEBLlI7PjwQB1eqZIxklInEW5dWbkrc3oEa+xLZZxHlwDwmRJhJB5h9F2rilky64awwv1BWNtv2+5lA2qsdDm4xRGQjnGSL4ew7gujdBPHn3Zv6vJlPAkCoLea5/ki+nQeyorkxdfMZjIhKBDUhex+tttmEo8TYWxObUQOYuPW7m7+eCWiwGlLvO/v1k4VUSEpQY5KHDQs5qVfr69WoH8/VDgDhXInVxgt3Q5Uqq2qRdx5kmj1AVSsc+E/45X3TY6KTKEPpjx6gXSVQdHY0c6aIU/+N1jqZBS+QzzvCcahL/cuPQrFjkXQBU2r962wcTMcQUvD8CThPFeXcjy93ZdrD2bDvBfnOuTv5+5g0+oaqs4yaEgWa18LrfeDhvrRG6LndoTWIAbOSy7qeDEUhovgK+4HXy4hecBCFLU5u/NZ/BVM0pI3aln1sBkqZnkN4EFgoFEehAeLd86lfhY1dd/gzQ3OBz/fhigzJjhFSIbt/HOzK8+kptcKJHHAsvXT9oiSFrt037Pvi103VlGiEfUuUXe9LbhdD1zINMkqRM4tO0fR++ILPQ0b0WjWiqA6o=
  app: spark-pheras-sqlite
